# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiencies', '0001_initial'),
        ('characters', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('speed', models.IntegerField()),
                ('alignment', models.CharField(max_length=20, null=True)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='characters.character')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='races', to='languages.language')),
                ('starting_proficiencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='proficiencies.proficiency')),
            ],
        ),
    ]
