# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('proficiencies_choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.TextField(max_length=200)),
                ('hit_die', models.IntegerField()),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='characters.character')),
                ('proficiencies_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='proficiencies_choices.proficiencychoices')),
            ],
        ),
    ]
