# Generated by Django 4.2.6 on 2023-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ability_scores', '0002_abilityscore'),
        ('spells_dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelldc',
            name='dc_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spellsDc', to='ability_scores.abilityscore'),
        ),
    ]
