# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiencies', '0001_initial'),
        ('equipments', '0001_initial'),
        ('skills', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alignment', models.CharField(default='Not Informed', max_length=20, null=True)),
                ('ability_scores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='characters.character')),
                ('equipments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='equipments.equipment')),
                ('languages', models.ManyToManyField(related_name='characters', to='languages.language')),
                ('proficiencies', models.ManyToManyField(related_name='characters', to='proficiencies.proficiency')),
                ('skills', models.ManyToManyField(related_name='characters', to='skills.skill')),
            ],
        ),
    ]
