# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(default='Not a magic user', related_name='characters', to='spells.spell'),
        ),
    ]
