# Generated by Django 4.2.6 on 2023-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ability_scores_characters', '0001_initial'),
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ability_scores',
        ),
        migrations.AddField(
            model_name='character',
            name='ability_score_character',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ability_scores_characters.abilityscorecharacter'),
        ),
    ]
