# Generated by Django 4.2.6 on 2023-10-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ability_scores_characters', '0001_initial'),
        ('characters', '0003_remove_character_ability_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ability_scores_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ability_scores_characters.abilityscorecharacter'),
        ),
    ]
