# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('spells_dc', '0001_initial'),
        ('spells_damage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('higher_level', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(max_length=200)),
                ('range', models.CharField(max_length=20)),
                ('components', models.CharField(max_length=60)),
                ('classes', models.ManyToManyField(related_name='spells', to='classes.class')),
                ('damage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='spells_damage.spelldamage')),
                ('dc', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spells', to='spells_dc.spelldc')),
            ],
        ),
    ]
