# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proficiencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=22, unique=True)),
                ('proficiency_choose', models.IntegerField()),
                ('proficiencies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficiencies_choices', to='proficiencies.proficiency')),
            ],
        ),
    ]
