# Generated by Django 4.2.6 on 2023-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells_dc', '0002_alter_spelldc_dc_type'),
        ('skills', '0002_alter_skill_ability_scores'),
        ('ability_scores', '0002_abilityscore'),
        ('ability_scores_characters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbilityScores',
        ),
        migrations.AddField(
            model_name='abilityscore',
            name='ability_characters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ability_score', to='ability_scores_characters.abilityscorecharacter'),
        ),
    ]
