# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('damage', models.CharField(max_length=10)),
                ('damage_type', models.CharField(max_length=12)),
                ('range', models.IntegerField()),
            ],
        ),
    ]
