# Generated by Django 4.2.6 on 2023-10-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ability_scores', '0002_abilityscore'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability_scores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='ability_scores.abilityscore'),
        ),
    ]
