# Generated by Django 4.2.6 on 2023-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(max_length=40)),
                ('damage_at_character_level', models.CharField(max_length=40, null=True)),
                ('damage_at_short_level', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
